Name:           samtools
Version:        0.1.19
Release:        3%{?dist}
Summary:        Fast and sensitive read alignment

License:        GPLv3
Group:		Other
URL:		http://samtools.sourceforge.net/       
Source0:        %{name}-%{version}.tar.bz2

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      x86_64

BuildRequires:  make gcc zlib-devel ncurses-devel


%description 

SAM (Sequence Alignment/Map) format is a generic format for storing large 
nucleotide sequence alignments. SAM aims to be a format that:

Is flexible enough to store all the alignment information generated by 
various alignment programs;
Is simple enough to be easily generated by alignment programs or converted 
from existing alignment formats;
Is compact in file size;
Allows most of operations on the alignment to work on a stream without 
loading the whole alignment into memory;
Allows the file to be indexed by genomic position to efficiently retrieve 
all reads aligning to a locus.

SAM Tools provide various utilities for manipulating alignments in the SAM 
format, including sorting, merging, indexing and generating alignments in 
a per-position format.

%package devel
Summary:        Header files for creating C extension to Samtools
Group:          Development/Libraries
Requires:       %{name} = %{version}-%{release}

%description devel
The samtools-devel package holds header files for C extensions

%prep
%setup -q -n %{name}-%{version}

%build
%{__make}
%{__make} razip

%install
rm -rf %{buildroot}

mkdir -p %{buildroot}%{_bindir}
install -m 0755 samtools %{buildroot}%{_bindir}
install -m 0755 razip %{buildroot}%{_bindir}
install -m 0755 bcftools/bcftools %{buildroot}%{_bindir}
install -m 0755 bcftools/vcfutils.pl %{buildroot}%{_bindir}
install -m 0755 misc/ace2sam %{buildroot}%{_bindir}
install -m 0755 misc/bamcheck %{buildroot}%{_bindir}
install -m 0755 misc/maq2sam-long %{buildroot}%{_bindir}
install -m 0755 misc/maq2sam-short %{buildroot}%{_bindir}
install -m 0755 misc/md5fa %{buildroot}%{_bindir}
install -m 0755 misc/md5sum-lite %{buildroot}%{_bindir}
install -m 0755 misc/plot-bamcheck %{buildroot}%{_bindir}
install -m 0755 misc/r2plot.lua %{buildroot}%{_bindir}
install -m 0755 misc/vcfutils.lua %{buildroot}%{_bindir}
install -m 0755 misc/wgsim %{buildroot}%{_bindir}
install -m 0755 misc/*.pl %{buildroot}%{_bindir}
mkdir -p %{buildroot}%{_libdir}
install -m 0644 libbam.a %{buildroot}%{_libdir}
mkdir -p %{buildroot}/usr/lib
install -m 0644 libbam.a %{buildroot}/usr/lib/
mkdir -p %{buildroot}%{_includedir}/bam
install -m 0644 *.h %{buildroot}%{_includedir}/bam/

%files
%defattr(-,root,root,-)
%doc AUTHORS NEWS samtools.1
%{_bindir}/samtools
%{_bindir}/razip
%{_bindir}/bcftools
%{_bindir}/ace2sam
%{_bindir}/bamcheck
%{_bindir}/maq2sam-long
%{_bindir}/maq2sam-short
%{_bindir}/md5fa
%{_bindir}/md5sum-lite
%{_bindir}/plot-bamcheck
%{_bindir}/wgsim
%{_bindir}/*.lua
%{_bindir}/*.pl

%files devel
%defattr(-,root,root,-)
%{_libdir}/libbam.a
/usr/lib/libbam.a
%{_includedir}/bam/*.h

%post devel
/sbin/ldconfig

%postun devel
/sbin/ldconfig

%changelog
* Mon Jun 17 2013 Brett Taylor <btaylor@wistar.org> - 0.1.19-2
- changed put *.h files in _includedir/bam/
- added post and postun sections
* Wed May 8 2013 Brett Taylor <btaylor@wistar.org> - 0.1.19
- updated to version 0.1.19
* Fri Feb 8 2013 Brett Taylor <btaylor@wistar.org> - 0.1.18
- initial version
